import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";

import "./globals.css";
import ClientProviders from "@/context/ClientProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Miles Rentals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script
          src="https://cdn.smileidentity.com/inline/v1/js/script.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${inter.className} noScrollBar`}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
