import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import ClientProviders from "@/context/ClientProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Miles Rentals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} noScrollBar`}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
